spring:
  data:
    mongodb:
#      authentication-database:
      uri: mongodb://admin:123456@49.233.5.107:27017/cw_doc


#spring:
#  data:
#    mongodb:
#      authentication-database: edasdb
#      uri: mongodb://dc_opener:#open_ovopark2020@47.96.11.161:27017/edasdb